Use AWS profiles
sodadata/soda-sql pull request #361
Opened 2021-06-22 13:09 UTC by Tonkonozhenko

2021-06-23 09:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sodadata/soda-sql?pullRequest=361) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/sodadata/soda-sql?pullRequest=361) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Tonkonozhenko<br/>:x: Alex Tonkonozhenko<br/><hr/>**Alex Tonkonozhenko** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sodadata/soda-sql?pullRequest=361) it.</sub>

2021-06-29 07:46 UTC, Tonkonozhenko commented
@vijaykiran could you review this, please?

2021-07-02 04:01 UTC, vijaykiran requested changes

2021-07-02 04:01 UTC, vijaykiran commented on packages/redshift/sodasql/dialects/redshift_dialect.py
> +        profile_name = parser.get_str_optional_env('profile_name')
This seems to be unused in credentials, I think you missed passing it to AWSCredentials

2021-07-02 04:02 UTC, vijaykiran commented
@Tonkonozhenko thanks again for the PR. Sorry for the delay, I was out of office.

2021-07-02 11:37 UTC, vijaykiran commented
https://github.com/sodadata/soda-sql/pull/372

2021-07-02 11:37 UTC, closed without merging