Add --offline flag to scan cli to skip sending results to Soda Cloud
sodadata/soda-sql pull request #448
Opened 2021-08-18 18:55 UTC by m1n0

- Added offline flag with default False
- No test added as it would only work on the builder, which would be a pointless test testing that passed parameter is used
- Removef default values for the `scan` cli method as we are using click default values for those params anyway
- Fixes #192

2021-08-18 21:20 UTC, vijaykiran requested changes
Just one minor change needed, otherwise LGTM

2021-08-18 21:20 UTC, vijaykiran commented on core/sodasql/cli/cli.py
> +        logging.info('Running in offline mode, scan results will NOT be pushed to Soda Cloud.')
Should be `logger.info`

2021-08-19 06:12 UTC, m1n0 commented on core/sodasql/cli/cli.py
> +        logging.info('Running in offline mode, scan results will NOT be pushed to Soda Cloud.')
ah yes thanks for the catch, fixed

2021-08-19 07:52 UTC, vijaykiran approved these changes

2021-08-19 07:53 UTC, merged